// Dosecraft drug catalog — single source of truth for drug metadata.
// Loaded via <script src="drugCatalog.js"> on index.html and game.html.

(function () {
  function drug(o) {
    const color = o.drugColor || o.color;
    const displayName = o.displayName || o.name;
    const genericName = o.genericName || o.generic;
    const gameType = o.gameType;
    return {
      id: o.id,
      name: displayName,
      displayName,
      brandName: o.brandName || displayName,
      generic: genericName,
      genericName,
      className: o.className || "",
      groupName: o.groupName || "",
      gameType,
      mechanicTemplate: o.mechanicTemplate || gameType,
      drugColor: color,
      color,
      bgGradient: o.bgGradient,
      mode: o.mode,
      tagline: o.tagline || "",
      description: o.description || "",
      howItWorks: o.howItWorks || "",
      encouragement: o.encouragement || "",
      winMessage: o.winMessage || "",
      paddleLabel: o.paddleLabel,
      brickLabel: o.brickLabel,
      ivigNote: o.ivigNote,
      pharmacistReviewNotes: o.pharmacistReviewNotes || "",
    };
  }

  window.DOSECRAFT_DRUGS = [
    drug({
      id: 1, displayName: "Zosyn", genericName: "Piperacillin-Tazobactam",
      className: "Penicillin/beta-lactam", groupName: "Penicillin",
      gameType: "breakout", drugColor: "#00d4c8", bgGradient: ["#021a18", "#04302c"],
      mode: "WALL BREAKER", tagline: "Breach the wall",
      paddleLabel: "ZOSYN", brickLabel: "Wall Section",
      description: "Zosyn is a powerful antibiotic used to treat serious infections of the lungs, abdomen, skin, kidneys, and bloodstream — especially when a single antibiotic may not be enough.",
      howItWorks: "Zosyn travels through your bloodstream and attacks the outer wall of bacteria, causing it to collapse. Without their protective wall, the bacteria cannot survive.",
      encouragement: "Your Zosyn infusion is actively fighting the infection right now.",
      winMessage: "Bacterial walls have collapsed. Infection is being cleared.",
    }),
    drug({
      id: 2, displayName: "Ancef", genericName: "Cefazolin",
      className: "Cephalosporin", groupName: "Cephalosporin",
      gameType: "breakout", drugColor: "#4f8ef7", bgGradient: ["#020d1f", "#041830"],
      mode: "WALL BREAKER", tagline: "Demolish defenses",
      paddleLabel: "ANCEF", brickLabel: "Wall Section",
      description: "Ancef (cefazolin) is commonly used to treat skin and soft tissue infections, bone infections, and to prevent infections around surgery.",
      howItWorks: "Ancef targets and destroys the structural wall that bacteria need to survive. As each wall section breaks down, the bacteria can no longer maintain their shape and die.",
      encouragement: "Your Ancef infusion is breaking down bacterial defenses right now.",
      winMessage: "Bacterial walls destroyed. Your infection is clearing.",
    }),
    drug({
      id: 3, displayName: "Rocephin", genericName: "Ceftriaxone",
      className: "Cephalosporin", groupName: "Cephalosporin",
      gameType: "breakout", drugColor: "#6366f1", bgGradient: ["#07041f", "#0e0830"],
      mode: "WALL BREAKER", tagline: "Destroy and clear",
      paddleLabel: "ROCEPHIN", brickLabel: "Wall Section",
      description: "Rocephin (ceftriaxone) is widely used to treat pneumonia, meningitis, urinary tract infections, Lyme disease, and many bloodstream infections.",
      howItWorks: "Rocephin circulates through your body and disrupts the construction of bacterial cell walls. Bacteria cannot repair or rebuild their walls and are eliminated.",
      encouragement: "Your Rocephin infusion is working to clear your infection.",
      winMessage: "Infection clearing. Rocephin has done its work.",
    }),
    drug({
      id: 4, displayName: "Maxipime", genericName: "Cefepime",
      className: "Cephalosporin", groupName: "Cephalosporin",
      gameType: "breakout", drugColor: "#818cf8", bgGradient: ["#05041f", "#0a0830"],
      mode: "WALL BREAKER", tagline: "Broad spectrum strike",
      paddleLabel: "MAXIPIME", brickLabel: "Wall Section",
      description: "Maxipime (cefepime) is a broad-spectrum antibiotic used for serious infections of the lungs, urinary tract, skin, and bloodstream.",
      howItWorks: "Maxipime targets and dismantles the cell walls that protect bacteria. Once the wall is gone, bacteria cannot survive and the infection begins to clear.",
      encouragement: "Your Maxipime infusion is actively clearing the infection.",
      winMessage: "Bacterial walls cleared. Maxipime is working.",
    }),
    drug({
      id: 5, displayName: "Invanz", genericName: "Ertapenem",
      className: "Carbapenem", groupName: "Carbapenem",
      gameType: "breakout", drugColor: "#f59e0b", bgGradient: ["#1a0f00", "#2e1a00"],
      mode: "WALL BREAKER", tagline: "Deep penetrator",
      paddleLabel: "INVANZ", brickLabel: "Wall Section",
      description: "Invanz (ertapenem) is a once-daily antibiotic used to treat complicated infections of the abdomen, pelvis, lungs, skin, and urinary tract.",
      howItWorks: "Invanz penetrates deep into infected tissue and destroys the protective outer walls of bacteria. Once compromised, bacteria cannot survive.",
      encouragement: "Your Invanz infusion is penetrating the infection and destroying bacteria.",
      winMessage: "Deep infection clearing. Invanz is working.",
    }),
    drug({
      id: 6, displayName: "Merrem", genericName: "Meropenem",
      className: "Carbapenem", groupName: "Carbapenem",
      gameType: "breakout", drugColor: "#fb923c", bgGradient: ["#1a0800", "#2e1000"],
      mode: "WALL BREAKER", tagline: "Maximum firepower",
      paddleLabel: "MERREM", brickLabel: "Wall Section",
      description: "Merrem (meropenem) is used for serious infections including pneumonia, meningitis, abdominal infections, and infections caused by resistant bacteria.",
      howItWorks: "Merrem rapidly targets and collapses the protective walls of bacteria throughout your body. It is one of the most powerful antibiotics available.",
      encouragement: "Your Merrem infusion is fighting hard against your infection right now.",
      winMessage: "Serious infection being cleared. Merrem is working.",
    }),
    drug({
      id: 7, displayName: "Vancomycin", genericName: "Vancomycin",
      className: "Glycopeptide", groupName: "Glycopeptides",
      gameType: "vanco", drugColor: "#c084fc", bgGradient: ["#0e0a1a", "#1a0d2e"],
      mode: "BLOCK ATTACK", tagline: "Block construction",
      paddleLabel: "VANCOMYCIN",
      description: "Vancomycin is used to treat serious infections caused by gram-positive bacteria, including MRSA — a type of staph infection resistant to many other antibiotics.",
      howItWorks: "Vancomycin latches onto the building blocks that bacteria use to construct their outer wall, blocking construction entirely. Without new wall material, bacteria weaken and die.",
      encouragement: "Your vancomycin infusion is blocking bacterial construction right now.",
      winMessage: "Bacterial wall construction blocked. Infection is clearing.",
    }),
    drug({
      id: 8, displayName: "Cubicin", genericName: "Daptomycin",
      className: "Lipopeptide", groupName: "Daptomycin",
      gameType: "dapto", drugColor: "#eab308", bgGradient: ["#0f0a00", "#1e1400"],
      mode: "MEMBRANE BREACH", tagline: "Punch through membranes",
      description: "Cubicin (daptomycin) is used to treat serious skin infections and bloodstream infections caused by gram-positive bacteria, including MRSA and VRE.",
      howItWorks: "Cubicin works by punching holes in the outer membrane of bacteria, causing them to lose the ions they need to survive. This rapidly kills the bacteria without harming your own cells.",
      encouragement: "Your Cubicin infusion is punching through bacterial membranes right now.",
      winMessage: "Bacterial membranes breached. Infection is being eliminated.",
    }),
    drug({
      id: 9, displayName: "Bivigam", genericName: "Immune Globulin Intravenous (Human) 10%",
      className: "Immunoglobulin", groupName: "Immunoglobulin",
      gameType: "ivig", drugColor: "#f4a261", bgGradient: ["#1a0e00", "#2e1a04"],
      mode: "IMMUNE DEFENSE", tagline: "Reinforce immunity",
      description: "Bivigam is an intravenous immunoglobulin (IVIG) therapy used primarily for people whose immune systems cannot produce enough antibodies on their own — a condition called primary immunodeficiency. By infusing concentrated antibodies from healthy donors, Bivigam gives your immune system the tools it needs to fight infections.",
      howItWorks: "Bivigam delivers a concentrated supply of IgG antibodies — the same antibodies healthy immune systems produce — directly into your bloodstream. These borrowed antibodies neutralize pathogens and help calm immune responses that may be misfiring. Because the dose must be large enough to flood your entire system, the infusion takes several hours.",
      encouragement: "The antibodies in your Bivigam infusion are actively protecting you right now.",
      winMessage: "Your immune system has been reinforced. Bivigam's borrowed antibodies are neutralizing threats and restoring balance.",
      ivigNote: "Bivigam is given directly into a vein (intravenously), allowing antibodies to reach your bloodstream quickly and in high concentration.",
    }),
    drug({
      id: 10, displayName: "Panzyga", genericName: "Immune Globulin Intravenous (Human) 10%",
      className: "Immunoglobulin", groupName: "Immunoglobulin",
      gameType: "ivig", drugColor: "#e76f51", bgGradient: ["#1a0800", "#2e1000"],
      mode: "IMMUNE DEFENSE", tagline: "Flood and rebalance",
      description: "Panzyga is an IVIG therapy used for primary immunodeficiency and certain autoimmune conditions. It provides high-concentration IgG antibodies sourced from thousands of healthy plasma donors, giving your immune system a powerful borrowed defense.",
      howItWorks: "Panzyga floods your bloodstream with IgG antibodies that do two important jobs: they neutralize bacteria, viruses, and toxins that your own immune system may not be able to handle, and they help regulate an overactive immune response by occupying receptors that would otherwise trigger autoimmune attacks on your own tissues.",
      encouragement: "Your Panzyga infusion is reinforcing your immune system as you sit here.",
      winMessage: "Pathogens neutralized and immune signals rebalanced. Panzyga has done its work.",
      ivigNote: "Panzyga is given intravenously. The slow infusion rate is intentional — it gives your body time to adjust to the incoming antibodies safely.",
    }),
    drug({
      id: 11, displayName: "Octagam", genericName: "Immune Globulin Intravenous (Human) 5% / 10%",
      className: "Immunoglobulin", groupName: "Immunoglobulin",
      gameType: "ivig", drugColor: "#e9c46a", bgGradient: ["#1a1400", "#2e2200"],
      mode: "IMMUNE DEFENSE", tagline: "Dual-action defense",
      description: "Octagam is an IVIG therapy used for primary immunodeficiency and certain autoimmune conditions. It delivers purified IgG antibodies to strengthen your immune response and help regulate immune activity that may be harming your own tissues.",
      howItWorks: "Octagam works in two ways. First, it provides antibodies your immune system is missing, allowing your body to recognize and destroy pathogens. Second, the high concentration of IgG floods immune receptors, crowding out the signals that cause the immune system to mistakenly attack the body's own cells.",
      encouragement: "Your Octagam infusion is working on two fronts — protecting and rebalancing your immune system.",
      winMessage: "Immune system strengthened and autoimmune signals crowded out. Octagam has completed its work.",
      ivigNote: "Octagam is available in two concentrations (5% and 10%). Your care team has selected the right formulation and rate for you specifically.",
    }),
    drug({
      id: 12, displayName: "Hyqvia", genericName: "Immune Globulin 10% with Recombinant Human Hyaluronidase",
      className: "Immunoglobulin", groupName: "Immunoglobulin",
      gameType: "ivig", drugColor: "#2a9d8f", bgGradient: ["#001a18", "#002e2a"],
      mode: "IMMUNE DEFENSE", tagline: "Steady absorption",
      description: "Hyqvia is a unique subcutaneous immunoglobulin (SCIG) therapy. Unlike traditional IVIG given through a vein, Hyqvia is given under the skin. It contains both IgG antibodies and an enzyme (hyaluronidase) that temporarily opens pathways in the tissue, allowing a large dose of antibodies to be absorbed steadily into the bloodstream.",
      howItWorks: "The hyaluronidase enzyme in Hyqvia gently loosens the tissue under your skin, creating space for the antibodies to spread and absorb gradually. This slow, steady absorption means the antibodies enter your bloodstream over a longer period — mimicking how your immune system would naturally maintain antibody levels.",
      encouragement: "Your Hyqvia dose is steadily absorbing and building your antibody levels right now.",
      winMessage: "Antibodies successfully absorbed. Hyqvia has steadily reinforced your immune defenses.",
      ivigNote: "Hyqvia is given subcutaneously (under the skin), not into a vein. The enzyme it contains temporarily opens tissue pathways so a full therapeutic dose can absorb gradually — a gentler process than traditional IV infusion.",
    }),
    drug({
      id: 13, displayName: "Penicillin G", genericName: "Penicillin G Potassium",
      className: "Penicillin/beta-lactam", groupName: "Penicillin",
      gameType: "breakout", drugColor: "#1ee0d4", bgGradient: ["#011a19", "#033330"],
      mode: "WALL BREAKER", tagline: "Break the cross-links",
      paddleLabel: "PENICILLIN G", brickLabel: "Wall Section",
      description: "Penicillin G is a foundational penicillin antibiotic used to treat many types of bacterial infections, including certain bloodstream, bone, joint, and soft tissue infections.",
      howItWorks: "Penicillin G interferes with bacterial cell-wall construction by targeting penicillin-binding proteins involved in peptidoglycan cross-linking. Without those links, the wall cannot hold together and bacteria die.",
      encouragement: "Your Penicillin G infusion is disrupting bacterial wall construction right now.",
      winMessage: "Bacterial walls weakened. Penicillin G is working.",
    }),
    drug({
      id: 14, displayName: "Dalvance", genericName: "dalbavancin",
      className: "Lipoglycopeptide", groupName: "Glycopeptides",
      gameType: "vanco", drugColor: "#a78bfa", bgGradient: ["#0c0818", "#160d28"],
      mode: "BLOCK ATTACK", tagline: "Stop the wall from locking",
      paddleLabel: "DALVANCE",
      description: "Dalvance (dalbavancin) is a lipoglycopeptide antibiotic used for certain serious bacterial skin infections.",
      howItWorks: "Dalvance attaches to the wall-building pieces bacteria use to make their outer shell. By grabbing those pieces before they can link together, it helps stop the wall from locking into place — so bacteria cannot build a strong, complete wall.",
      encouragement: "Your Dalvance infusion is stopping bacterial walls from locking together right now.",
      winMessage: "Wall cross-linking blocked. Dalvance is working.",
    }),
  ];

  window.DOSECRAFT_DRUG_GROUPS = [
    { id: "penicillin", label: "Penicillin Antibiotics", homepageLabel: "Penicillin", color: "#00d4c8", drugIds: [1, 13] },
    { id: "cephalosporin", label: "Cephalosporin Antibiotics", homepageLabel: "Cephalosporin", color: "#6366f1", drugIds: [2, 3, 4] },
    { id: "carbapenem", label: "Carbapenem Antibiotics", homepageLabel: "Carbapenem", color: "#f59e0b", drugIds: [5, 6] },
    { id: "glycopeptide", label: "Glycopeptide Antibiotics", homepageLabel: "Glycopeptides", color: "#c084fc", drugIds: [7, 14] },
    { id: "daptomycin", label: "Cubicin (Daptomycin)", homepageLabel: "Daptomycin", color: "#eab308", drugIds: [8] },
    { id: "immunoglobulin", label: "Immunoglobulin Therapy (IVIG / SCIG)", homepageLabel: "Immunoglobulin", color: "#f4a261", drugIds: [9, 10, 11, 12] },
  ];

  window.DOSECRAFT_MECHANIC_TILES = [
    { label: "Wall Breaker", icon: "🧱", color: "#00d4c8", desc: "Cell wall antibiotics" },
    { label: "Block Attack", icon: "🔒", color: "#c084fc", desc: "Glycopeptide antibiotics" },
    { label: "Membrane Breach", icon: "💥", color: "#eab308", desc: "Membrane antibiotics" },
    { label: "Immune Defense", icon: "🛡", color: "#f4a261", desc: "IVIG / SCIG" },
  ];
})();
